language: csharp
solution: ./Hangfire.PostgreSql.sln

before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono .nuget/nuget.exe # Output NuGet's version number
  
install:
  - sudo apt-get install nunit-console
  - mono .nuget/nuget.exe restore ./Hangfire.PostgreSql.sln -Verbosity detailed
  #- mono .nuget/nuget.exe install xunit.runner.console -OutputDirectory ./src/packages

install:
  - nuget restore ./Hangfire.PostgreSql.sln

script:
  - xbuild ./Hangfire.PostgreSql.sln
  - nunit-console ./tests/Hangfire.PostgreSql.Tests/bin/Debug/Hangfire.PostgreSql.Tests.dll