SET search_path = 'hangfire';

DO
$$
    BEGIN
        IF EXISTS(SELECT 1 FROM "SCHEMA" WHERE "VERSION"::integer >= 15) THEN
            RAISE EXCEPTION 'version-already-applied';
        END IF;
    END
$$;

CREATE INDEX IX_HANGFIRE_JOB_EXPIREAT ON "JOB" ("EXPIREAT");
CREATE INDEX IX_HANGFIRE_LIST_EXPIREAT ON "LIST" ("EXPIREAT");
CREATE INDEX IX_HANGFIRE_SET_EXPIREAT ON "SET" ("EXPIREAT");
CREATE INDEX IX_HANGFIRE_HASH_EXPIREAT ON "HASH" ("EXPIREAT");

RESET search_path;
