SET search_path = 'hangfire';

DO
$$
    BEGIN
        IF EXISTS(SELECT 1 FROM "SCHEMA" WHERE "VERSION"::integer >= 11) THEN
            RAISE EXCEPTION 'version-already-applied';
        END IF;
    END
$$;

ALTER TABLE "COUNTER"
    ALTER COLUMN "ID" TYPE BIGINT;
ALTER TABLE "HASH"
    ALTER COLUMN "ID" TYPE BIGINT;
ALTER TABLE "JOB"
    ALTER COLUMN "ID" TYPE BIGINT;
ALTER TABLE "JOB"
    ALTER COLUMN "STATEID" TYPE BIGINT;
ALTER TABLE "STATE"
    ALTER COLUMN "ID" TYPE BIGINT;
ALTER TABLE "STATE"
    ALTER COLUMN "JOBID" TYPE BIGINT;
ALTER TABLE "JOBPARAMETER"
    ALTER COLUMN "ID" TYPE BIGINT;
ALTER TABLE "JOBPARAMETER"
    ALTER COLUMN "JOBID" TYPE BIGINT;
ALTER TABLE "JOBQUEUE"
    ALTER COLUMN "ID" TYPE BIGINT;
ALTER TABLE "JOBQUEUE"
    ALTER COLUMN "JOBID" TYPE BIGINT;
ALTER TABLE "LIST"
    ALTER COLUMN "ID" TYPE BIGINT;
ALTER TABLE "SET"
    ALTER COLUMN "ID" TYPE BIGINT;

RESET search_path;