SET search_path = 'hangfire';
--
-- Table structure for table `Schema`
--

DO
$$
    BEGIN
        IF EXISTS(SELECT 1 FROM "SCHEMA" WHERE "VERSION"::integer >= 4) THEN
            RAISE EXCEPTION 'version-already-applied';
        END IF;
    END
$$;

ALTER TABLE "COUNTER"
    ADD COLUMN "UPDATECOUNT" integer NOT NULL DEFAULT 0;
ALTER TABLE "LOCK"
    ADD COLUMN "UPDATECOUNT" integer NOT NULL DEFAULT 0;
ALTER TABLE "HASH"
    ADD COLUMN "UPDATECOUNT" integer NOT NULL DEFAULT 0;
ALTER TABLE "JOB"
    ADD COLUMN "UPDATECOUNT" integer NOT NULL DEFAULT 0;
ALTER TABLE "JOBPARAMETER"
    ADD COLUMN "UPDATECOUNT" integer NOT NULL DEFAULT 0;
ALTER TABLE "JOBQUEUE"
    ADD COLUMN "UPDATECOUNT" integer NOT NULL DEFAULT 0;
ALTER TABLE "LIST"
    ADD COLUMN "UPDATECOUNT" integer NOT NULL DEFAULT 0;
ALTER TABLE "SERVER"
    ADD COLUMN "UPDATECOUNT" integer NOT NULL DEFAULT 0;
ALTER TABLE "SET"
    ADD COLUMN "UPDATECOUNT" integer NOT NULL DEFAULT 0;
ALTER TABLE "STATE"
    ADD COLUMN "UPDATECOUNT" integer NOT NULL DEFAULT 0;

RESET search_path;