SET search_path = 'hangfire';

DO
$$
    BEGIN
        IF EXISTS(SELECT 1 FROM "SCHEMA" WHERE "VERSION"::integer >= 12) THEN
            RAISE EXCEPTION 'version-already-applied';
        END IF;
    END
$$;

ALTER TABLE "COUNTER"
    ALTER COLUMN "KEY" TYPE TEXT;
ALTER TABLE "HASH"
    ALTER COLUMN "KEY" TYPE TEXT;
ALTER TABLE "HASH"
    ALTER COLUMN "FIELD" TYPE TEXT;
ALTER TABLE "JOB"
    ALTER COLUMN "STATENAME" TYPE TEXT;
ALTER TABLE "LIST"
    ALTER COLUMN "KEY" TYPE TEXT;
ALTER TABLE "SERVER"
    ALTER COLUMN "ID" TYPE TEXT;
ALTER TABLE "SET"
    ALTER COLUMN "KEY" TYPE TEXT;
ALTER TABLE "JOBPARAMETER"
    ALTER COLUMN "NAME" TYPE TEXT;
ALTER TABLE "STATE"
    ALTER COLUMN "NAME" TYPE TEXT;
ALTER TABLE "STATE"
    ALTER COLUMN "REASON" TYPE TEXT;

RESET search_path;