SET search_path = 'hangfire';

DELETE FROM "HANGFIRE"."COUNTER";
DELETE FROM "HANGFIRE"."HASH";
DELETE FROM "HANGFIRE"."JOB";
DELETE FROM "HANGFIRE"."JOBPARAMETER";
DELETE FROM "HANGFIRE"."JOBQUEUE";
DELETE FROM "HANGFIRE"."LIST";
DELETE FROM "HANGFIRE"."LOCK";
DELETE FROM "HANGFIRE"."SERVER";
DELETE FROM "HANGFIRE"."SET";
DELETE FROM "HANGFIRE"."STATE";